### PR TITLE
PR to fix Issue #64

### LINKED ISSUE #64: Incorporate here package
Ideally, this repository would have a `lessons` folder in which each Part would be placed within. A barrier to this is the importing of data files: right now, they are hard coded according to the path, starting in `Part2.R`.

A better approach would be to place the files within the `lessons` folders, and use the `here` package to properly create the import. This would be a good instruction point, as `here` is used in basically all other R workshops.

The best place to do this is in `Part2.R`. However, these changes would require going through all scripts and making the appropriate changes to the filepaths.

### PR DESCRIPTION
**Pull request by asteves**
This PR does the following: 

- Introduces the `here` package in Part2.R 
- Provides examples in Part2.R showing how the here package looks similar to the base `read.csv()` structure. 
- Updates all file paths to include calls to here
- Provides another example of installing packages and loading a packages. 
- Updates all solutions file paths to include call to here
- Updates README to add contributors and updated web links to contributors. 

Closes #64 

@pssachdeva

### CODE REVIEW

**Comment by pssachdeva** [comment]
I will give this a review, but let's hold off on merging since it's rather short notice before the intensives next week.

File: lessons/Part2.R [hunk 1]
```diff
@@ -41,6 +41,30 @@ gap <- read.csv(file = "data/gapminder-FiveYearData.csv",
                 # Tell R to code anything defined here as NA
                 na.strings = c("", " ", "?", "NONE", "none"))
 
+## Navigating directory structures can be confusing. We have to remember a lot of aspects of of where our files are located. This can be fragile and dependent on the way we order files on our computers, which are often different than the way our friends and colleagues do it. 
+
+## One way to make this easier is to take advantage of the here R package. The here package enables easy file referencing by using the top level directory of our project to build the file paths. For more information, check out the here package [https://here.r-lib.org/articles/here.html]
```
Comment (pssachdeva) [inline lessons/Part2.R]: Can you make all reference to the `here` package in quotations whenever the occur in the comments? Since we're not in Markdown we don't get the benefit of code font, but I'd like to separate it so people know we're talking about the package.

File: lessons/Part2.R [hunk 2]
```diff
@@ -41,6 +41,30 @@ gap <- read.csv(file = "data/gapminder-FiveYearData.csv",
                 # Tell R to code anything defined here as NA
                 na.strings = c("", " ", "?", "NONE", "none"))
 
+## Navigating directory structures can be confusing. We have to remember a lot of aspects of of where our files are located. This can be fragile and dependent on the way we order files on our computers, which are often different than the way our friends and colleagues do it. 
+
```
Comment (pssachdeva) [inline lessons/Part2.R:45]: Can you add a short discussion on packages in R? I noticed we don't actually do it when we install dplyr; it'd be useful to have that here.

**Review by pssachdeva — CHANGES_REQUESTED** [review]
This looks good, just asked for a couple small tweaks. Thanks for making the changes.

File: lessons/Part2.R (hunk 1 above)
Comment (asteves) [reply lessons/Part2.R]: Done

File: lessons/Part2.R (hunk 2 above)
Comment (asteves) [reply lessons/Part2.R:45]: Done.

**Comment by asteves** [comment]
Comments resolved. I'll let @pssachdeva decide when it is reasonable to merge.

**Comment by pssachdeva** [comment]
We can go ahead and merge this, but this PR needs to be [rebased](https://docs.github.com/en/get-started/using-git/about-git-rebase) since other changes have occurred in the meantime. If you're not familiar with rebasing, feel free to reach out and we can chat through the process.

**Comment by asteves** [comment]
What am I rebasing it off of?

**Comment by pssachdeva** [comment]
Make sure your `main` branch is up to date. Then, rebase off `main`.

**Comment by asteves** [comment]
@pssachdeva I think this is correct. Assuming it is, please go ahead and merge. @pssachdeva

**Comment by pssachdeva** [comment]
I think it may have ended up doing a merge commit. At any rate, that's fine - everything looks good, so let's merge it.
